source_keys <- c("alachua co crim law enf", "gainesville", "archer", "hawthorne",
                 "high springs", "newberry", "university of florida", "alachua",
                 "micanopy", "waldo", "santa fe college", "alachua crim law enf",
                 "alachua game fwf comm", "fhp gainesville", "baker co crim law enf",
                 "baker crim law enf", "baker game fwf comm", "fhp baker co",
                 "bay co crim law enf", "panama city", "cedar grove", "mexico beach",
                 "springfield", "panama city beach", "lynn haven", "fsu panama city",
                 "parker", "bay crim law enf", "bay game fwf comm", "fhp panama city",
                 "bradford co crim law enf", "starke", "bradford crim law enf",
                 "bradford game fwf comm", "fhp starke", "brevard co crim law enf",
                 "cocoa", "cocoa beach", "indialantic", "indian harbor beach",
                 "melbourne beach", "rockledge", "satellite beach", "titusville",
                 "palm bay", "melbourne village", "west melbourne", "melbourne int airport",
                 "brevard crim law enf", "brevard game fwf comm", "fhp melbourne",
                 "broward co crim law enf", "dania", "deerfield beach", "fort lauderdale",
                 "hallandale", "hollywood", "plantation", "pompano beach", "pembroke pines",
                 "wilton manors", "cooper city", "coconut creek", "davie", "hillsboro beach",
                 "lauderdale by the sea", "lauderdale lakes", "lauderhill", "lighthouse point",
                 "margate", "miramar", "north lauderdale", "oakland park", "sea ranch lakes",
                 "sunrise", "coral springs", "pembroke park", "tamarac", "ft lauderdale intl airport",
                 "parkland", "seminole indian reservation", "broward crim law enf",
                 "broward division of insurance fraud", "broward game fwf comm",
                 "weston", "fhp fort lauderdale", "port everglades", "calhoun crim law enf",
                 "calhoun game fwf comm", "fhp calhoun co", "dnr did not report",
                 "charlotte co crim law enf", "punta gorda", "charlotte crim law enf",
                 "charlotte game fwf comm", "fhp charlotte co", "citrus co crim law enf",
                 "crystal river", "citrus crim law enf", "citrus game fwf comm",
                 "fhp citrus co", "clay co crim law enf", "orange park", "clay crim law enf",
                 "clay game fwf comm", "fhp clay co", "collier co crim law enf",
                 "naples", "marco island", "collier crim law enf", "collier game fwf comm",
                 "fhp everglades city", "lake city", "columbia crim law enf",
                 "columbia game fwf comm", "fhp lake city", "miami dade", "bal harbour village",
                 "coral gables", "florida city", "hialeah", "homestead", "miami",
                 "miami beach", "miami shores", "miami springs", "north miami beach",
                 "opa locka", "surfside", "biscayne park", "el portal", "hialeah gardens",
                 "north bay village", "north miami", "south miami", "virginia gardens",
                 "west miami", "bay harbor islands", "golden beach", "indian creek village",
                 "medley", "sweetwater", "fdle miami", "florida international university",
                 "miami dade public schools", "miccosukee public safety department",
                 "dade crim law enf", "key biscayne", "sunny isles beach", "dade division of insurance fraud",
                 "dade game fwf comm", "fhp miami", "aventura", "village of pinecrest",
                 "de soto co crim law enf", "arcadia", "desoto crim law enf",
                 "desoto game fwf comm", "fhp arcadia", "dixie co crim law enf",
                 "cross city", "dixie crim law enf", "dixie game fwf comm", "fhp cross city",
                 "atlantic beach", "jacksonville sheriffs office", "jacksonville beach",
                 "neptune beach", "fdle jacksonville ra", "university of north florida",
                 "jacksonville aviation authority", "duval crim law enf", "duval division of insurance fraud",
                 "duval game fwf comm", "fhp jacksonville", "escambia co crim law enf",
                 "fdle pensacola ra", "university of west florida", "escambia crim law enf",
                 "escambia div of insurance fraud", "escambia game fwf comm",
                 "fhp pensacola", "pensacola state college", "flagler co crim law enf",
                 "bunnell", "flagler beach", "flagler crim law enf", "flagler game fwf comm",
                 "fhp flagler co", "franklin co crim law enf", "apalachicola",
                 "franklin crim law enf", "franklin game fwf comm", "fhp apalachicola",
                 "gadsden co crim law enf", "quincy public safety department",
                 "havana", "gretna", "midway", "greensboro", "gadsden crim law enf",
                 "gadsden game fwf comm", "fhp quincy", "gilchrist co crim law enf",
                 "trenton", "fl gilchrist insp gen ", "gilchrist game fwf comm",
                 "fhp gilchrist co", "glades co crim law enf", "glades crim law enf",
                 "glades game fwf comm", "fhp glades co", "gulf co crim law enf",
                 "port st joe", "gulf crim law enf", "gulf game fwf comm", "fhp gulf co",
                 "hamilton co crim law enf", "jasper", "hamilton crim law enf",
                 "hamilton game fwf comm", "fhp hamilton co", "hardee co crim law enf",
                 "bowling green", "wauchula", "hardee crim law enf", "hardee game fwf comm",
                 "fhp hardee co", "hendry co crim law enf", "clewiston", "hendry crim law enf",
                 "hendry game fwf comm", "fhp hendry co", "hernando co crim law enf",
                 "brooksville", "hernando crim law enf", "hernando game fwf comm",
                 "fhp brooksville", "highlands co crim law enf", "avon park",
                 "lake placid", "sebring", "highlands crim law enf", "highlands game fwf comm",
                 "fhp lake placid", "hillsborough county sheriffs offc", "plant city",
                 "tampa", "temple terrace", "fdle tampa tboc", "tampa international airport",
                 "univ of south florida tampa", "hillsborough crim law enf", "hillsborough div of insurance fraud",
                 "hillsborough game fwf comm", "fhp tampa", "holmes co crim law enf",
                 "bonifay", "holmes crim law enf", "holmes game fwf comm", "fhp holmes co",
                 "indian river county sheriffs offc", "fellsmere", "sebastian",
                 "vero beach", "indian river shores", "indian river crim law enf",
                 "indian river game fwf comm", "fhp indian river co", "jackson co crim law enf",
                 "marianna", "cottondale", "jackson crim law enf", "jackson game fwf comm",
                 "fhp marianna", "jefferson co crim law enf", "monticello", "jefferson crim law enf",
                 "jefferson game fwf comm", "fhp jefferson co", "lafayette crim law enf",
                 "lafayette game fwf comm", "fhp lafayette co", "lake co crim law enf",
                 "eustis", "leesburg", "clermont", "fruitland park", "groveland",
                 "howey in the hills", "mascotte", "mount dora", "tavares", "umatilla",
                 "lady lake", "astatula", "lake crim law enf", "lake game fwf comm",
                 "fhp leesburg", "lee co crim law enf", "fort myers", "cape coral",
                 "sanibel", "lee county airport", "fdle fort myers ra", "florida gulf coast university",
                 "lee crim law enf", "lee division of insurance fraud", "lee game fwf comm",
                 "fhp fort myers", "leon co crim law enf", "tallahassee", "fdle tallahassee",
                 "leon crim law enf", "florida state university", "florida a m university",
                 "leon game fwf comm", "florida capitol police", "division of state fire marshall",
                 "leon division of insurance fraud", "fhp tallahassee", "levy co crim law enf",
                 "cedar key", "chiefland", "inglis", "williston", "levy crim law enf",
                 "levy game fwf comm", "fhp inglis", "liberty co crim law enf",
                 "liberty crim law enf", "liberty game fwf comm", "fhp liberty co",
                 "madison co crim law enf", "madison", "greenville", "madison crim law enf",
                 "madison game fwf comm", "fhp madison", "manatee co crim law enf",
                 "bradenton", "bradenton beach", "holmes beach", "longboat key",
                 "palmetto", "manatee crim law enf", "manatee game fwf comm",
                 "fhp bradenton", "marion co crim law enf", "ocala", "belleview",
                 "dunnellon", "marion crim law enf", "marion game fwf comm", "fhp ocala",
                 "martin co crim law enf", "stuart", "jupiter island", "sewalls point",
                 "martin crim law enf", "martin game fwf comm", "fhp martin co",
                 "monroe co crim law enf", "key west", "monroe crim law enf",
                 "monroe game fwf comm", "fhp marathon", "nassau co crim law enf",
                 "nassau crim law enf", "nassau game fwf comm", "fhp nassau co",
                 "okaloosa co crim law enf", "crestview", "fort walton", "valparaiso",
                 "shalimar", "mary esther", "okaloosa crim law enf", "okaloosa game fwf comm",
                 "fhp crestview", "okeechobee co crim law enf", "okeechobee",
                 "okeechobee crim law enf", "okeechobee game fwf comm", "fhp okeechobee co",
                 "orange co crim law enf", "apopka", "maitland", "ocoee", "orlando",
                 "winter garden", "winter park", "oakland", "windermere", "edgewood",
                 "fdle orlando ra", "university of central florida", "orange crim law enf",
                 "orange division of insurance fraud", "orange game fwf comm",
                 "fhp orlando", "osceola co crim law enf", "st cloud", "kissimmee",
                 "osceola crim law enf", "osceola game fwf comm", "fhp kissimmee",
                 "palm beach co crim law enf", "belle glade", "boca raton", "boynton beach",
                 "delray beach", "lake worth", "palm beach", "riviera beach",
                 "west palm beach", "atlantis", "greenacres city", "gulfstream",
                 "town of hypoluxo", "juno beach", "jupiter", "jupiter inlet colony",
                 "lake park", "lantana", "manalapan", "mangonia park", "north palm beach",
                 "ocean ridge", "pahokee", "palm beach gardens", "south bay",
                 "south palm beach", "tequesta", "palm beach shores", "florida atlantic university",
                 "highland beach", "palm beach crim law enf", "palm beach county school",
                 "lake clarke shores", "palm beach div of insurance fraud", "palm beach game fwf comm",
                 "fhp palm beach turnpike station", "fhp lantana", "wellington",
                 "pasco co crim law enf", "dade city", "new port richey", "zephyrhills",
                 "port richey", "pasco crim law enf", "pasco game fwf comm", "fhp pasco co",
                 "pinellas co crim law enf", "belleair", "belleair bluffs", "clearwater",
                 "dunedin", "gulfport", "indian rocks beach", "kenneth city",
                 "largo", "madeira beach", "seminole", "oldsmar", "pinellas park",
                 "redington beaches", "safety harbor", "st petersburg", "st pete beach",
                 "south pasadena", "indian shores", "tarpon springs", "treasure island",
                 "belleair beach", "north redington beach", "pinellas county schools campus",
                 "st petersburg clearwater airp", "univ of s florida pinellas",
                 "pinellas crim law enf", "pinellas game fwf comm", "fhp pinellas park",
                 "polk co crim law enf", "auburndale", "bartow", "davenport",
                 "eagle lake", "fort meade", "frostproof", "haines city", "lake alfred",
                 "lake hamilton", "lakeland", "lake wales", "mulberry", "winter haven",
                 "polk crim law enf", "polk game fwf comm", "fhp lakeland", "putnam co crim law enf",
                 "palatka", "crescent city", "welaka", "putnam crim law enf",
                 "putnam game fwf comm", "fhp palatka", "st johns co crim law enf",
                 "st augustine", "st augustine beach", "florida sch for deaf and blind",
                 "st johns crim law enf", "st johns game fwf comm", "fhp st augustine",
                 "st lucie co crim law enf", "fort pierce", "port st lucie", "st lucie crim law enf",
                 "st lucie game fwf comm", "fhp fort pierce", "santa rosa co crim law enf",
                 "milton", "gulf breeze", "santa rosa crim law enf", "santa rosa game fwf comm",
                 "fhp santa rosa co", "sarasota co crim law enf", "sarasota",
                 "venice", "north port", "sarasota bradenton intl airport", "new college of florida",
                 "sarasota crim law enf", "sarasota game fwf comm", "fhp venice",
                 "seminole co crim law enf", "altamonte springs", "casselberry",
                 "longwood", "oviedo", "sanford", "winter springs", "lake mary",
                 "seminole crim law enf", "seminole game fwf comm", "fhp seminole co",
                 "sumter co crim law enf", "bushnell", "center hill", "webster",
                 "wildwood", "sumter crim law enf", "sumter game fwf comm", "fhp sumter co",
                 "suwannee co crim law enf", "live oak", "suwannee crim law enf",
                 "suwannee game fwf comm", "fhp suwannee co", "taylor co crim law enf",
                 "perry", "taylor crim law enf", "taylor game fwf comm", "fhp perry",
                 "union co crim law enf", "union crim law enf", "union game fwf comm",
                 "fhp union co", "volusia co crim law enf", "daytona beach", "deland",
                 "new smyrna beach", "ormond beach", "daytona beach shores", "edgewater",
                 "holly hill", "lake helen", "oak hill", "orange city", "port orange",
                 "south daytona", "ponce inlet", "volusia county beach patrol",
                 "volusia crim law enf", "volusia game fwf comm", "fhp deland",
                 "wakulla co crim law enf", "wakulla crim law enf", "wakulla game fwf comm",
                 "fhp wakulla co", "walton co crim law enf", "defuniak springs",
                 "walton crim law enf", "walton game fwf comm", "fhp walton co",
                 "washington co crim law enf", "chipley", "washington crim law enf",
                 "washington game fwf comm", "fhp washington co", "florida", "hampton",
                 "melbourne", "town of southwest ranches", "calhoun co crim law enf",
                 "blountstown", "green cove springs", "columbia co crim law enf",
                 "baldwin", "pensacola", "carrabelle", "gilchrist insp gen ",
                 "white springs", "zolfo springs", "graceville", "sneads", "lafayette co crim law enf",
                 "tcc", "fernandina beach", "niceville", "orange co crim law enf ",
                 "eatonville", "palm springs", "royal palm beach", "dundee", "interlachen",
                 "daytona beach regional airport", "west park", "inverness", "miami lakes",
                 "chattahoochee", "jennings", "altha", "de soto co crim law enf ",
                 "coleman", "lawtey", "dnr did not report", "miami gardens mdpd ",
                 "palmetto bay", "doral mdpd ", "duval county school board", "dabt duval",
                 "key colony beach", " data for crestview for the second half of was impacted by changes in their ucr reporting system ",
                 "santa fe community college", "aventura", "miami gardens", "palmetto bay",
                 "doral", "jacksonville", "jacksonville port authority", " baldwin",
                 "baldiwn arrests are being reported by the jacksonville ", "pensacola jr college",
                 "gilchrist crim law enf", "florida statewide", "town of cutler bay police dept ",
                 "dnr did not report ", " hillsborough county sheriffs offc",
                 "please contact the agency for possible revised data ", "minneola",
                 "pinellas div of insurance fraud", " eagle lake", " eagle lake offenses are being reported by the polk co sheriff s office ",
                 "cooper city", "dabt alachua", "dabt bay", "dabt bradford", "dabt brevard",
                 "dabt broward", "dabt calhoun", "dabt charlotte", "dabt citrus",
                 "dabt clay", "dabt collier", "dabt columbia", "dabt dade", "dabt desoto",
                 "dabt dixie", "dabt escambia", "dabt franklin", "dabt gadsden",
                 "dabt gilchrist", "dabt glades", "dabt gulf", "dabt hamilton",
                 "dabt hardee", "dabt hendry", "dabt hernando", "dabt highlands",
                 "dabt hillsborough", "dabt holmes", "dabt indian river", "dabt jackson",
                 "dabt jefferson", "dabt lafayette", "dabt lake", "dabt lee",
                 "dabt tallahassee", "dabt levy", "dabt liberty", "dabt madison",
                 "dabt manatee", "dabt marion", "dabt martin", "dabt monroe",
                 "dabt nassau", "dabt okaloosa", "dabt okeechobee", "dabt orange",
                 "belle isles", "dabt osceola", "dabt palm beach", "dabt pasco",
                 "dabt pinellas", "dabt polk", "dabt putnam", "dabt st johns",
                 "dabt st johns", "dabt santa rosa", "dabt sarasota", "dabt seminole",
                 "dabt sumter", "dabt suwannee", "dabt taylor", "dabt union",
                 "dabt volusia", "dabt wakulla", "dabt walton", "dabt washington",
                 "florida", "nw fl beaches inter airport", "edison state college",
                 "alachua doc inspector general", "baker doc inspector general",
                 "nw fl beaches inter airport", "bradford doc inspector general",
                 "calhoun doc inspector general", "franklin doc inspector general",
                 "gilchrist doc inspecrot general", "hamilton doc inspector general",
                 "jackson doc inspector general", "jefferson doc inspector general",
                 "lafayette doc inspector general", "lake doc inspector general",
                 "madison doc inspector general", "marion doc inspector general",
                 "martin doc inspector general", "okeechobee doc inspector general",
                 "polk doc inspector general", "dabt st lucie", "santa rosa doc inspector general",
                 "sumter doc inspector general", "suwannee doc inspector general",
                 "taylor doc inspector general", "wakulla doc inspector general",
                 "washington doc inspector general", "me ico beach", "bay doc inspector general",
                 "broward doc inspector general", "columbia doc inspector general",
                 "dixie doc inspector general", "dabt flagler", "gadsden doc inspector general",
                 "gulf doc inspector general", "orange doc inspector general",
                 "town of hypolu o", "port canaveral", "charlotte doc inspector general",
                 "cutler bay", "florida department of corrections", "brevard doc inspector general",
                 "citrus doc inspector general", "clay doc inspector general",
                 "collier doc inspector general", "dade doc inspector general",
                 "de soto doc inspector general", "dabt de soto", "duval doc inspector general",
                 "escambia doc inspector general", "flagler doc inspector general",
                 "gilchrist doc inspector general", "glades doc inspector general",
                 "hardee doc inspector general", "hendry doc inspector general",
                 "hernando doc inspector general", "highlands doc inspector general",
                 "hillsborough doc inspector general", "holmes doc inspector general",
                 "indian river doc inspector general", "lee doc inspector general",
                 "dabt leon", "leon doc inspector general", "fhp dhsmv", "levy doc inspector general",
                 "liberty doc inspector general", "manatee doc inspector general",
                 "monroe doc inspector general", "nassau doc inspector general",
                 "okaloosa doc inspector general", "osceola doc inspector general",
                 "palm beach doc inspector general", "pasco doc inspector general",
                 "pinellas doc inspector general", "florida polytechnic university",
                 "putnam doc inspector general", "st johns doc inspector general",
                 "st lucie doc inspector general", "sarasota doc inspector general",
                 "seminole doc inspector general", "union doc inspector general",
                 "volusia doc inspector general", "walton doc inspector general",
                 "dnr did not report", "desoto doc inspector general", "dnr did not report"
)

choice_keys <- c("alachua", "gainesville", "archer", "hawthorne", "high springs",
                 "newberry", "university of florida", "lacrosse", "alachua", "alachua co dle-gainesvil",
                 "micanopy", "waldo", "santa fe commun college", "alachua county marine pt",
                 "alachua co bev-gainesvil", "alachua hp, gainesville", "alachua co div beverage",
                 "alachua co crim law enf", "alachua co game fwf comm", "alachua highway patrol",
                 "alachua co marine patrol", "baker", "macclenny", "baker county marine patr",
                 "baker highway patrol", "port st. joe", "baker co div beverage",
                 "baker co crim law enf", "baker co game fwf comm", "baker highway patrol",
                 "baker co marine patrol", "bay", "panama city", "callaway", "cedar grove",
                 "mexico beach", "springfield", "panama city beach", "lynn haven",
                 "bay co fwf com- panama c", "bay co dle-panama city", "florida st. univ.-panama",
                 "parker", "mp bay co, panama city", "bay co bev enf-panama ci",
                 "bay hp, panama city", "bay co div beverage", "bay co criminal law enf",
                 "bay co game fwf comm", "bay highway patrol", "bay county marine patrol",
                 "bradford", "starke", "hampton", "lawtey", "bradford county marine p",
                 "bradford hp, starke", "bradford co div beverage", "bradford co crim law enf",
                 "bradford co game fwf com", "bradford highway patrol", "bradford co marine ptl",
                 "brevard", "cape canaveral", "cocoa", "cocoa beach", "eau gallie",
                 "indialantic", "indian harbour beach", "melbourne", "melbourne beach",
                 "rockledge", "satellite beach", "titusville", "palm bay", "palm shores",
                 "merritt island", "melbourne village", "west melbourne", "brevard co dle-melbourne",
                 "melbourne int. airport", "brevard co ofc pub safet", "mp brevard co, melbourne",
                 "brevard co bevereage enf", "brevard hp, melbourne", "brevard co shp-cocoa",
                 "brevard co div beverage", "brevard co crim law enf", "brevard co game fwf comm",
                 "brevard highway patrol", "brevard co marine patrol", "broward",
                 "dania", "deerfield beach", "fort lauderdale", "hallandale",
                 "hollywood", "plantation", "pompano beach", "pembroke pines",
                 "wilton manors", "cooper city", "coconut creek", "davie", "hacienda village",
                 "hillsboro beach", "hollywood ridge farms", "lauderdale-by-the-sea",
                 "lauderdale lakes", "lauderhill", "lighthouse point", "margate",
                 "miramar", "north lauderdale", "oakland park", "sea ranch lakes",
                 "sunrise", "coral springs", "pembroke park", "tamarac", "broward co airport pol",
                 "parkland", "seminole tribal", "broward county marine pt", "broward co bev-lauderhil",
                 "broward co dept insuranc", "weston", "broward hp, ft. lauderda",
                 "port everglades", "broward co div beverage", "broward co crim law enf",
                 "broward co game fwf comm", "broward highway patrol", "broward co marine patrol",
                 "calhoun", "altha", "blountstown", "calhoun county marine pt",
                 "calhoun highway patrol", "calhoun co div beverage", "calhoun co crim law enf",
                 "calhoun co game fwf comm", "calhoun highway patrol", "calhoun co marine patrol",
                 "charlotte", "punta gorda", "fl marine ptl charlotte", "charlotte highway patrol",
                 "charlotte co div beverag", "charlotte co crim law en", "charlotte co game fwf co",
                 "charlotte highway patrol", "charlotte co marine ptl", "citrus",
                 "crystal river", "inverness", "mp citrus co, crystl riv", "citrus highway patrol",
                 "citrus co div beverage", "citrus co crim law enf", "citrus co game fwf comm",
                 "citrus highway patrol", "citrus co marine patrol", "clay", "green cove springs",
                 "orange park", "keystone heights", "columbia co game fwf com",
                 "florida marine ptl clay", "clay highway patrol", "clay co div beverage",
                 "clay co crim law enf", "clay co game fwf comm", "clay highway patrol",
                 "clay co marine patrol", "collier", "naples", "everglades city",
                 "marco island", "collier county marine pt", "collier hp, everglades c",
                 "collier co div beverage", "collier co crim law enf", "collier co game fwf comm",
                 "collier highway patrol", "collier co marine patrol", "columbia",
                 "lake city", "fort white", "columbia co fwf lake cty", "columbia co. marine patr",
                 "columbia hp, lake city", "columbia co div beverage", "columbia co crim law enf",
                 "columbia highway patrol", "columbia co marine ptl", "miami-dade",
                 "bal harbour village", "coral gables", "florida city", "hialeah",
                 "homestead", "miami", "miami beach", "miami shores", "miami springs",
                 "north miami beach", "opa locka", "surfside", "biscayne park",
                 "el portal", "hialeah gardens", "north bay village", "north miami",
                 "south miami", "virginia gardens", "west miami", "bay harbor island",
                 "golden beach", "indian creek village", "medley", "sweetwater",
                 "dle dade co., miami", "florida international un", "dade co pub school sec d",
                 "dade co treas ins fraud", "miccosukee", "mp dade co., miami",
                 "key biscayne", "dade co beverage enf", "sunny isles beach",
                 "dade co. dept of insuran", "us cust serv sect comm", "dade hp, miami",
                 "aventura", "village of pinecrest", "dade co div beverage", "dade co crim law enf",
                 "dade co game fwf comm", "dade highway patrol", "dade co marine patrol",
                 "desoto", "arcadia", "de soto county marine pt", "desoto co hp- arcadia",
                 "de soto co div beverage", "de soto co crim law enf", "de soto co game fwf comm",
                 "de soto highway patrol", "de soto co marine patrol", "dixie",
                 "cross city", "horseshoe beach", "dixie county marine patr",
                 "dixie hp, cross city", "dixie co div beverage", "dixie co crim law enf",
                 "dixie co game fwf comm", "dixie highway patrol", "dixie co marine patrol",
                 "duval", "atlantic beach", "jacksonville", "jacksonville beach",
                 "neptune beach", "dle duval co, jacksonvil", "university of north flor",
                 "jacksonville airport aut", "baldwin", "duval co mp jacksonville",
                 "duval co bev enforcement", "duval co dept of insuran", "duval hp, jacksonville",
                 "duval co div beverage", "duval co crim law enf", "duval co game fwf comm",
                 "duval highway patrol", "duval co marine patrol", "escambia",
                 "pensacola", "century", "escambia.co dle pensacol", "university of west flori",
                 "mp escambia co pensacola", "escambia co beverage enf", "escambia co dept insuran",
                 "escambia hp, pensacola", "pensacola junior college", "escambia co div beverage",
                 "escambia co crim law enf", "escambia co game fwf com", "escambia highway patrol",
                 "escambia co marine ptl", "flagler", "bunnell", "flagler beach",
                 "flagler county marine pt", "flagler highway patrol", "flagler co div beverage",
                 "flagler co crim law enf", "flagler co game fwf comm", "flagler highway patrol",
                 "flagler co marine patrol", "franklin", "apalachicola", "carrabelle",
                 "mp franklin,carrabelle", "franklin hp apalachicola", "franklin co div beverage",
                 "franklin co crim law enf", "franklin co game fwf com", "franklin highway patrol",
                 "franklin co marine ptl", "gadsden", "quincy", "chattahoochee",
                 "havana", "gretna", "midway", "greensboro", "gadsden county marine pt",
                 "gadsden hp, quincy", "gadsden co div beverage", "gadsden co crim law enf",
                 "gadsden co game fwf comm", "gadsden highway patrol", "gadsden co marine patrol",
                 "gilchrist", "trenton", "gilchrist co. marine ptr", "gilchrist highway patrol",
                 "gilchrist co div beverag", "gilchrist co crim law en", "gilchrist co game fwf co",
                 "gilchrist highway patrol", "gilchrist co marine ptl", "glades",
                 "moore haven", "glades county marine ptr", "glades highway patrol",
                 "glades co div beverage", "glades co crim law enf", "glades co game fwf comm",
                 "glades highway patrol", "glades co marine patrol", "gulf", "wewahitchka",
                 "gulf county marine patro", "gulf highway patrol", "gulf co div beverage",
                 "gulf co crim law enf", "gulf co game fwf comm", "gulf highway patrol",
                 "gulf co marine patrol", "hamilton", "jasper", "jennings", "white springs",
                 "hamilton co ag bureau", "hamilton co. marine patr", "hamilton highway patrol",
                 "hamilton co div beverage", "hamilton co crim law enf", "hamilton co game fwf com",
                 "hamilton highway patrol", "hamilton co marine patro", "hardee",
                 "bowling green", "wauchula", "zolfo springs", "hardee county marine ptr",
                 "hardee highway patrol", "hardee co div beverage", "hardee co crim law enf",
                 "hardee co game fwf comm", "hardee highway patrol", "hardee co marine patrol",
                 "hendry", "clewiston", "seminole indian pd", "hendry county marine ptr",
                 "hendry highway patrol", "hendry co div beverage", "hendry co crim law enf",
                 "hendry co game fwf comm", "hendry highway patrol", "hendry co marine patrol",
                 "hernando", "brooksville", "hernando co. marine patr", "hernando hp, brooksville",
                 "hernando co div beverage", "hernando co crim law enf", "hernando co game fwf com",
                 "hernando highway patrol", "hernando co marine ptl", "highlands",
                 "avon park", "lake placid", "sebring", "sebring airport authorit",
                 "highlands co dle sebring", "highlands co. marine ptr", "highlands hp lake placid",
                 "highlands co div beverag", "highlands co crim law en", "highlands co game fwf co",
                 "highlands highway patrol", "highlands co marine ptl", "hillsborough",
                 "plant city", "tampa", "temple terrace", "dle hillsborough, tampa",
                 "tampa international airp", "univ of s. fl - tampa", "mp hillsborough co tampa",
                 "hillsborough co bev tamp", "hillsborough co dpt insu", "hillsborough hp, tampa",
                 "hillsborough co div bev", "hillsborough co crim law", "hillsborough co game fwf",
                 "hillsborough highway pat", "hillsborough co marine p", "university of tampa",
                 "holmes", "bonifay", "holmes county marine ptr", "holmes highway patrol",
                 "holmes co div beverage", "holmes co crim law enf", "holmes co game fwf comm",
                 "holmes highway patrol", "holmes co marine patrol", "indian river",
                 "fellsmere", "sebastian", "vero beach", "indian river shores",
                 "indian river co marine p", "indian river highway pat", "indian river co div bev",
                 "indian river co crim law", "indian river co game fwf", "indian river highway pat",
                 "indian river co marine p", "jackson", "marianna", "cottondale",
                 "graceville", "malone", "sneads", "grand ridge", "alford", "jackson county marine pt",
                 "jackson co. bev. enf. bu", "jackson hp, marianna", "jackson co div beverage",
                 "jackson co crim law enf", "jackson co game fwf comm", "jackson highway patrol",
                 "jackson co marine patrol", "jefferson", "monticello", "fl marine ptrl jefferson",
                 "jefferson highway patrol", "jefferson co div beverag", "jefferson co crim law en",
                 "jefferson co game fwf co", "jefferson highway patrol", "jefferson co marine ptl",
                 "lafayette", "mayo", "lafayette co marine patr", "lafayette highway patrol",
                 "lafayette co div beverag", "lafayette co crim law en", "lafayette co game fwf co",
                 "lafayette highway patrol", "lafayette co marine ptl", "lake",
                 "eustis", "leesburg", "clermont", "fruitland park", "groveland",
                 "howey-in-the-hills", "mascotte", "minneola", "montverde", "mount dora",
                 "tavares", "umatilla", "lady lake", "astatula", "lake county marine patro",
                 "lake hp, leesburg", "lake co div beverage", "lake co crim law enf",
                 "lake co game fwf comm", "lake highway patrol", "lake co marine patrol",
                 "lee", "fort myers", "cape coral", "sanibel", "lee co. port authority",
                 "dle lee co-fort myers", "fl gulf coast university", "mp lee co-fort myers",
                 "lee co bev enf-fort myer", "lee co. dept of insuranc", "lee hp, fort myers",
                 "lee co div beverage", "lee co crim law enf", "lee co game fwf comm",
                 "lee highway patrol", "lee co marine patrol", "leon", "fla dept of law enforce",
                 "fla division of beverage", "tallahassee", "leon co. dle fd off tall",
                 "mp leon co, enforcement", "fla st univ-tallahassee", "florida a&m university",
                 "game & fwf commission", "capitol police", "leon co dle park patrol",
                 "leon co. dot tallahasee", "leon co. marks & brands", "div state fire marshall",
                 "leon co. agr & con talla", "leon co. ag rd gd tallah", "leon co. lottery sec tal",
                 "st treasurer's off div i", "leon co bev enf tallahas", "leon hp, tallahassee",
                 "leon co fhp hq tallahass", "leon co div beverage", "leon co crim law enf",
                 "leon co game fwf comm", "leon highway patrol", "leon co marine patrol",
                 "levy", "cedar key", "chiefland", "inglis", "williston", "levy county marine patro",
                 "levy hp, inglis", "levy co div beverage", "levy co crim law enf",
                 "levy co game fwf comm", "levy highway patrol", "levy co marine patrol",
                 "liberty", "liberty county marine pt", "liberty highway patrol",
                 "liberty co div beverage", "liberty co crim law enf", "liberty co game fwf comm",
                 "liberty highway patrol", "liberty co marine patrol", "madison",
                 "madison", "greenville", "lee", "madison county marine pt", "madison highway patrol",
                 "madison co div beverage", "madison co crim law enf", "madison co game fwf comm",
                 "madison highway patrol", "madison co marine patrol", "manatee",
                 "anna maria", "bradenton", "bradenton beach", "holmes beach",
                 "longboat key", "palmetto", "manatee county marine pt", "manatee hp, bradenton",
                 "manatee co div beverage", "manatee co crim law enf", "manatee co game fwf comm",
                 "manatee highway patrol", "manatee co marine patrol", "marion",
                 "ocala", "belleview", "dunnellon", "marion co fwf com ocalia",
                 "marion county marine ptr", "marion co bev enf ocalia", "marion hp, ocala",
                 "marion co div beverage", "marion co crim law enf", "marion co game fwf comm",
                 "marion highway patrol", "marion co marine patrol", "martin",
                 "stuart", "jupiter island", "sewall's point", "martin county marine ptr",
                 "martin highway patrol", "martin co div beverage", "martin co crim law enf",
                 "martin co game fwf comm", "martin highway patrol", "martin co marine patrol",
                 "monroe", "key west", "key colony beach", "layton", "munson island",
                 "monroe co dle key west", "mp monroe co, marathon", "monroe co bev en key wes",
                 "monroe hp, marathon", "monroe co shp key west", "monroe co div beverage",
                 "monroe co crim law enf", "monroe co game fwf comm", "monroe highway patrol",
                 "monroe co marine patrol", "nassau", "fernandina beach", "callahan",
                 "hilliard", "nassau county marine ptr", "nassau highway patrol",
                 "nassau co div beverage", "nassau co crim law enf", "nassau co game fwf comm",
                 "nassau highway patrol", "nassau co marine patrol", "okaloosa",
                 "crestview", "fort walton beach", "niceville", "valparaiso",
                 "shalimar", "cinco bayou", "okaloosa county air term", "laurel hill",
                 "mary esther", "okaloosa co dle ft wtn b", "okaloosa county marine p",
                 "windermere", "okaloosa hp, crestview", "okaloosa co div beverage",
                 "okaloosa co crim law enf", "okaloosa co game fwf com", "okaloosa highway patrol",
                 "okaloosa co marine patro", "okeechobee", "okeechobee", "okeechobee co marine ptr",
                 "okeechobee highway patro", "okeechobee co div bev", "okeechobee co crim law",
                 "okeechobee co game fwf", "okeechobee highway patro", "okeechobee co marine ptl",
                 "orange", "apopka", "maitland", "ocoee", "orlando", "winter garden",
                 "winter park", "eatonville", "oakland", "edgewood", "dle orange co, orlando",
                 "orange co constable di 1", "orange co const dis 11 a", "university of central fl",
                 "orange county marine ptr", "orange co bev enf orland", "orange co dpt of insuran",
                 "orange hp, orlando", "orange co shp tnpk orlan", "orange co div beverage",
                 "orange co crim law enf", "orange co game fwf comm", "orange highway patrol",
                 "orange co marine patrol", "osceola", "st. cloud", "kissimmee",
                 "osceola county marine pt", "osceola hp, kissimmee", "osceola co div beverage",
                 "osceola co crim law enf", "osceola co game fsf comm", "osceola highway patrol",
                 "osceola co marine patrol", "palm beach", "belle glade", "boca raton",
                 "boynton beach", "delray beach", "lake worth", "palm beach",
                 "riviera beach", "west palm beach", "atlantis", "briny breezes",
                 "glen ridge", "city of greenacres", "gulf stream", "hypoluxo",
                 "juno beach", "jupiter", "jupiter inlet colony", "lake park",
                 "lantana", "manalapan", "mangonia park", "north palm beach",
                 "ocean ridge", "pahokee", "palm beach gardens", "palm springs",
                 "royal palm beach", "south bay", "south palm beach", "tequesta",
                 "cloud lake", "palm beach shores", "palm beach co dle fld of",
                 "florida atlantic univ", "highland beach", "mp palm beach county",
                 "palm beach co dnr jupite", "palm beach co. schools", "lake clarke shores",
                 "palm beach bev enf bur", "palm beach co dpt insura", "palm beach hp pb turnpik",
                 "palm beach shp pahokee", "palm beach hp, lantana", "wellington",
                 "palm beach co div bev", "palm beach co crim law", "palm beach co game & fwf",
                 "palm beach highway patro", "palm beach co marine ptl", "pasco",
                 "dade city", "new port richey", "zephyrhills", "port richey",
                 "san antonio", "st. leo", "pasco county marine patr", "pasco highway patrol",
                 "pasco co div beverage", "pasco co crim law enf", "pasco co game fwf comm",
                 "pasco highway patrol", "pasco co marine patrol", "pinellas",
                 "belleair", "belleair bluffs", "clearwater", "dunedin", "gulfport",
                 "indian rocks beach", "kenneth city", "largo", "madeira beach",
                 "seminole", "oldsmar", "pinellas park", "redington beaches",
                 "safety harbor", "st. petersburg", "st. pete beach", "south pasadena",
                 "indian shores", "tarpon springs", "treasure island", "belleair beach",
                 "pinellas co dle clearwat", "redington shores", "north redington beach",
                 "pinellas co schools", "st. pete-clearwater airp", "univ of s fl-st. peterbg",
                 "winter haven", "mp pinellas, st. petersb", "pinellas co bev enf bure",
                 "pinellas hp pinellas prk", "seminole", "pinellas co div beverage",
                 "pinellas co crim law enf", "pinellas co game fwf com", "pinellas highway patrol",
                 "pinellas co marine ptl", "polk", "auburndale", "bartow", "davenport",
                 "dundee", "eagle lake", "fort meade", "frostproof", "haines city",
                 "lake alfred", "lake hamilton", "lakeland", "lake wales", "mulberry",
                 "polk city", "polk co fwf comm lakelan", "polk co dle lakeland",
                 "polk county marine patro", "polk co bev enf bureau", "polk hp, lakeland",
                 "polk co div beverage", "polk co crim law enf", "polk co game fwf comm",
                 "polk highway patrol", "polk co marine patrol", "putnam", "palatka",
                 "crescent city", "interlachen", "welaka", "pomona park", "putnam county marine ptr",
                 "putnam hp, palatka", "putnam co div beverage", "putnam co crim law enf",
                 "putnam co game fwf comm", "putnam highway patrol", "putnam co marine patrol",
                 "st. johns", "st. augustine", "st. augustine beach", "castillo de san marcos",
                 "hastings", "ponte vedra beach", "fl sch for deaf & blind", "st. johns co. marine ptr",
                 "st. johns hp st. augusti", "st. johns co div beverag", "st. johns co crim law en",
                 "st. johns co game fwf cm", "st. johns highway patrol", "st. johns co marine ptrl",
                 "st. lucie", "fort pierce", "port st. lucie", "st. lucie co marine patr",
                 "st. lucie co bev enf bur", "st. lucie hp ft. pierce", "st. lucie co div beverag",
                 "st. lucie co crim law en", "st. lucie co game fwf cm", "st. lucie highway ptrl",
                 "st. lucie co marine ptrl", "santa rosa", "milton", "gulf breeze",
                 "jay", "santa rosa co marine ptr", "santa rosa highway patro",
                 "santa rosa co div bev", "santa rosa co crim law", "santa rosa co game fwf",
                 "santa rosa highway patro", "santa rosa co marine ptl", "sarasota",
                 "sarasota", "venice", "north port", "sarasota co dle sarasota",
                 "sarasota/bradenton i air", "univ of s fl - sarasota", "sarasota co. marine patr",
                 "sarasota co bev enf bure", "sarasota hp, venice", "sarasota co div beverage",
                 "sarasota co crim law enf", "sarasota co game fwf com", "sarasota highway patrol",
                 "sarasota co marine ptl", "seminole", "altamonte springs", "casselberry",
                 "longwood", "oviedo", "sanford", "winter springs", "lake mary",
                 "seminole county marine p", "seminole highway patrol", "seminole co div beverage",
                 "seminole co crim law enf", "seminole co game fwf com", "seminole highway patrol",
                 "seminole co marine ptl", "sumter", "bushnell", "center hill",
                 "coleman", "webster", "wildwood", "sumter county marine ptr",
                 "sumter highway patrol", "sumter co div beverage", "sumter co crim law enf",
                 "sumter co game fwf comm", "sumter highway patrol", "sumter co marine patrol",
                 "suwannee", "branford", "live oak", "suwanee co fdle live oak",
                 "suwannee co. marine patr", "suwanne co bev enf live", "suwannee highway patrol",
                 "suwannee co div beverage", "suwannee co crim law enf", "suwannee co game fwf com",
                 "suwannee highway patrol", "suwannee co marine patro", "taylor",
                 "perry", "taylor county marine ptr", "taylor hp, perry", "taylor co div beverage",
                 "taylor co crim law enf", "taylor co game fwf comm", "taylor highway patrol",
                 "taylor co marine patrol", "union", "union county marine patr",
                 "union highway patrol", "union co div beverage", "union co crim law enf",
                 "union co game fwf comm", "union highway patrol", "volusia",
                 "daytona beach", "deland", "new smyrna beach", "ormond beach",
                 "daytona beach shores", "edgewater", "holly hill", "lake helen",
                 "oak hill", "orange city", "pierson", "port orange", "south daytona",
                 "ponce inlet", "daytona beach int airpor", "volusia co dle s daytona",
                 "volusia co. beach mgmt.", "volusia co. marine patro", "volusia co beve daytona",
                 "volusia hp, deland", "volusia co fhp daytona b", "volusia co div beverage",
                 "volusia co crim law enf", "volusia co game fwf comm", "volusia highway patrol",
                 "volusia co marine patrol", "wakulla", "sopchoppy", "wakulla co. marine patro",
                 "wakulla highway patrol", "wakulla co div beverage", "wakulla co crim law enf",
                 "wakulla co game fwf comm", "wakulla highway patrol", "wakulla co marine patrol",
                 "walton", "de funiak springs", "paxton", "walton co. marine patrol",
                 "walton highway patrol", "walton co div beverage", "walton co crim law enf",
                 "walton co game fwf comm", "walton highway patrol", "walton co marine patrol",
                 "washington", "chipley", "vernon", "washington co. marine pt",
                 "washington highway patro", "washington co div bev", "washington co crim law",
                 "washington co game fwf", "washington highway patro", "washington co marine ptl",
                 "florida hp, headquarters")

id_keys <- c("FL00100", "FL00101", "FL00102", "FL00103", "FL00104", "FL00105",
             "FL00106", "FL00107", "FL00108", "FL00109", "FL00119", "FL00125",
             "FL00127", "FL00140", "FL00150", "FL00190", "FL001DB", "FL001DL",
             "FL001GM", "FL001HP", "FL001MP", "FL00200", "FL00201", "FL00240",
             "FL00290", "FL02301", "FL002DB", "FL002DL", "FL002GM", "FL002HP",
             "FL002MP", "FL00300", "FL00301", "FL00302", "FL00303", "FL00304",
             "FL00305", "FL00306", "FL00307", "FL00309", "FL00310", "FL00311",
             "FL00326", "FL00340", "FL00350", "FL00390", "FL003DB", "FL003DL",
             "FL003GM", "FL003HP", "FL003MP", "FL00400", "FL00401", "FL00402",
             "FL00403", "FL00440", "FL00490", "FL004DB", "FL004DL", "FL004GM",
             "FL004HP", "FL004MP", "FL00500", "FL00501", "FL00502", "FL00503",
             "FL00504", "FL00505", "FL00506", "FL00507", "FL00508", "FL00509",
             "FL00510", "FL00511", "FL00512", "FL00513", "FL00514", "FL00515",
             "FL00516", "FL00517", "FL00518", "FL00519", "FL00540", "FL00550",
             "FL00590", "FL00591", "FL005DB", "FL005DL", "FL005GM", "FL005HP",
             "FL005MP", "FL00600", "FL00601", "FL00602", "FL00603", "FL00604",
             "FL00605", "FL00606", "FL00607", "FL00608", "FL00609", "FL00610",
             "FL00611", "FL00612", "FL00613", "FL00614", "FL00615", "FL00616",
             "FL00617", "FL00618", "FL00620", "FL00621", "FL00622", "FL00623",
             "FL00624", "FL00626", "FL00627", "FL00628", "FL00630", "FL00631",
             "FL00632", "FL00633", "FL00634", "FL00640", "FL00650", "FL00670",
             "FL00688", "FL00690", "FL00699", "FL006DB", "FL006DL", "FL006GM",
             "FL006HP", "FL006MP", "FL00700", "FL00701", "FL00702", "FL00740",
             "FL00790", "FL007DB", "FL007DL", "FL007GM", "FL007HP", "FL007MP",
             "FL00800", "FL00802", "FL00840", "FL00890", "FL008DB", "FL008DL",
             "FL008GM", "FL008HP", "FL008MP", "FL00900", "FL00901", "FL00902",
             "FL00940", "FL00990", "FL009DB", "FL009DL", "FL009GM", "FL009HP",
             "FL009MP", "FL01000", "FL01001", "FL01002", "FL01003", "FL012GM",
             "FL01040", "FL01090", "FL010DB", "FL010DL", "FL010GM", "FL010HP",
             "FL010MP", "FL01100", "FL01101", "FL01102", "FL01103", "FL01140",
             "FL01190", "FL011DB", "FL011DL", "FL011GM", "FL011HP", "FL011MP",
             "FL01200", "FL01201", "FL01202", "FL01203", "FL01240", "FL01290",
             "FL012DB", "FL012DL", "FL012HP", "FL012MP", "FL01300", "FL01301",
             "FL01302", "FL01303", "FL01304", "FL01305", "FL01306", "FL01307",
             "FL01308", "FL01309", "FL01310", "FL01312", "FL01313", "FL01314",
             "FL01315", "FL01316", "FL01317", "FL01318", "FL01319", "FL01320",
             "FL01321", "FL01322", "FL01324", "FL01325", "FL01327", "FL01329",
             "FL01330", "FL01331", "FL01337", "FL01338", "FL01339", "FL01340",
             "FL01343", "FL01350", "FL01351", "FL01370", "FL01380", "FL01390",
             "FL01391", "FL01392", "FL013DB", "FL013DL", "FL013GM", "FL013HP",
             "FL013MP", "FL01400", "FL01401", "FL01440", "FL01490", "FL014DB",
             "FL014DL", "FL014GM", "FL014HP", "FL014MP", "FL01500", "FL01501",
             "FL01502", "FL01540", "FL01590", "FL015DB", "FL015DL", "FL015GM",
             "FL015HP", "FL015MP", "FL01600", "FL01601", "FL01602", "FL01603",
             "FL01604", "FL01605", "FL01606", "FL01607", "FL01625", "FL01640",
             "FL01650", "FL01670", "FL01690", "FL016DB", "FL016DL", "FL016GM",
             "FL016HP", "FL016MP", "FL01700", "FL01701", "FL01702", "FL01703",
             "FL01704", "FL01740", "FL01750", "FL01770", "FL01790", "FL01791",
             "FL017DB", "FL017DL", "FL017GM", "FL017HP", "FL017MP", "FL01800",
             "FL01801", "FL01802", "FL01840", "FL01890", "FL018DB", "FL018DL",
             "FL018GM", "FL018HP", "FL018MP", "FL01900", "FL01901", "FL01902",
             "FL01940", "FL01990", "FL019DB", "FL019DL", "FL019GM", "FL019HP",
             "FL019MP", "FL02000", "FL02001", "FL02002", "FL02003", "FL02004",
             "FL02005", "FL02006", "FL02040", "FL02090", "FL020DB", "FL020DL",
             "FL020GM", "FL020HP", "FL020MP", "FL02100", "FL02102", "FL02140",
             "FL02190", "FL021DB", "FL021DL", "FL021GM", "FL021HP", "FL021MP",
             "FL02200", "FL02201", "FL02240", "FL02290", "FL022DB", "FL022DL",
             "FL022GM", "FL022HP", "FL022MP", "FL02300", "FL02302", "FL02340",
             "FL02390", "FL023DB", "FL023DL", "FL023GM", "FL023HP", "FL023MP",
             "FL02400", "FL02401", "FL02402", "FL02403", "FL02404", "FL02440",
             "FL02490", "FL024DB", "FL024DL", "FL024GM", "FL024HP", "FL024MP",
             "FL02500", "FL02501", "FL02502", "FL02503", "FL02540", "FL02590",
             "FL025DB", "FL025DL", "FL025GM", "FL025HP", "FL025MP", "FL02600",
             "FL02601", "FL02603", "FL02640", "FL02690", "FL026DB", "FL026DL",
             "FL026GM", "FL026HP", "FL026MP", "FL02700", "FL02701", "FL02740",
             "FL02790", "FL027DB", "FL027DL", "FL027GM", "FL027HP", "FL027MP",
             "FL02800", "FL02801", "FL02802", "FL02803", "FL02804", "FL02805",
             "FL02840", "FL02890", "FL028DB", "FL028DL", "FL028GM", "FL028HP",
             "FL028MP", "FL02900", "FL02901", "FL02902", "FL02903", "FL02905",
             "FL02906", "FL02907", "FL02940", "FL02950", "FL02970", "FL02990",
             "FL029DB", "FL029DL", "FL029GM", "FL029HP", "FL029MP", "FL029UT",
             "FL03000", "FL03001", "FL03040", "FL03090", "FL030DB", "FL030DL",
             "FL030GM", "FL030HP", "FL030MP", "FL03100", "FL03101", "FL03102",
             "FL03103", "FL03104", "FL03140", "FL03190", "FL031DB", "FL031DL",
             "FL031GM", "FL031HP", "FL031MP", "FL03200", "FL03201", "FL03202",
             "FL03203", "FL03204", "FL03205", "FL03206", "FL03207", "FL03240",
             "FL03250", "FL03290", "FL032DB", "FL032DL", "FL032GM", "FL032HP",
             "FL032MP", "FL03300", "FL03301", "FL03340", "FL03390", "FL033DB",
             "FL033DL", "FL033GM", "FL033HP", "FL033MP", "FL03400", "FL03401",
             "FL03440", "FL03490", "FL034DB", "FL034DL", "FL034GM", "FL034HP",
             "FL034MP", "FL03500", "FL03501", "FL03502", "FL03503", "FL03504",
             "FL03505", "FL03506", "FL03507", "FL03508", "FL03509", "FL03510",
             "FL03511", "FL03512", "FL03513", "FL03514", "FL03540", "FL03590",
             "FL035DB", "FL035DL", "FL035GM", "FL035HP", "FL035MP", "FL03600",
             "FL03601", "FL03602", "FL03603", "FL03604", "FL03605", "FL03607",
             "FL03640", "FL03650", "FL03670", "FL03690", "FL036DB", "FL036DL",
             "FL036GM", "FL036HP", "FL036MP", "FL03700", "FL03701", "FL03702",
             "FL03703", "FL03704", "FL03705", "FL03706", "FL03707", "FL03708",
             "FL03709", "FL03710", "FL03711", "FL03712", "FL03713", "FL03714",
             "FL03715", "FL03716", "FL03717", "FL03750", "FL03790", "FL03791",
             "FL037DB", "FL037DL", "FL037GM", "FL037HP", "FL037MP", "FL03800",
             "FL03801", "FL03802", "FL03803", "FL03804", "FL03840", "FL03890",
             "FL038DB", "FL038DL", "FL038GM", "FL038HP", "FL038MP", "FL03900",
             "FL03940", "FL03990", "FL039DB", "FL039DL", "FL039GM", "FL039HP",
             "FL039MP", "FL04000", "FL04001", "FL04002", "FL04003", "FL04040",
             "FL04090", "FL040DB", "FL040DL", "FL040GM", "FL040HP", "FL040MP",
             "FL04100", "FL04101", "FL04102", "FL04103", "FL04104", "FL04105",
             "FL04106", "FL04140", "FL04190", "FL041DB", "FL041DL", "FL041GM",
             "FL041HP", "FL041MP", "FL04200", "FL04201", "FL04202", "FL04203",
             "FL04204", "FL04240", "FL04250", "FL04290", "FL042DB", "FL042DL",
             "FL042GM", "FL042HP", "FL042MP", "FL04300", "FL04301", "FL04302",
             "FL04303", "FL04340", "FL04390", "FL043DB", "FL043DL", "FL043GM",
             "FL043HP", "FL043MP", "FL04400", "FL04401", "FL04402", "FL04403",
             "FL04404", "FL04405", "FL04440", "FL04450", "FL04490", "FL04491",
             "FL044DB", "FL044DL", "FL044GM", "FL044HP", "FL044MP", "FL04500",
             "FL04501", "FL04502", "FL04503", "FL04540", "FL04590", "FL045DB",
             "FL045DL", "FL045GM", "FL045HP", "FL045MP", "FL04600", "FL04601",
             "FL04602", "FL04603", "FL04604", "FL04605", "FL04606", "FL04607",
             "FL04608", "FL04609", "FL04610", "FL04640", "FL04809", "FL04690",
             "FL046DB", "FL046DL", "FL046GM", "FL046HP", "FL046MP", "FL04700",
             "FL04701", "FL04740", "FL04790", "FL047DB", "FL047DL", "FL047GM",
             "FL047HP", "FL047MP", "FL04800", "FL04801", "FL04802", "FL04803",
             "FL04804", "FL04805", "FL04806", "FL04807", "FL04808", "FL04810",
             "FL04811", "FL04812", "FL04813", "FL04814", "FL04840", "FL04850",
             "FL04870", "FL04890", "FL04891", "FL048DB", "FL048DL", "FL048GM",
             "FL048HP", "FL048MP", "FL04900", "FL04901", "FL04902", "FL04940",
             "FL04990", "FL049DB", "FL049DL", "FL049GM", "FL049HP", "FL049MP",
             "FL05000", "FL05001", "FL05002", "FL05003", "FL05004", "FL05005",
             "FL05006", "FL05007", "FL05008", "FL05009", "FL05010", "FL05011",
             "FL05012", "FL05013", "FL05015", "FL05016", "FL05017", "FL05018",
             "FL05019", "FL05020", "FL05021", "FL05022", "FL05023", "FL05024",
             "FL05025", "FL05026", "FL05027", "FL05028", "FL05029", "FL05030",
             "FL05031", "FL05032", "FL05033", "FL05035", "FL05037", "FL05038",
             "FL05040", "FL05041", "FL05042", "FL05050", "FL05051", "FL05070",
             "FL05090", "FL05091", "FL05092", "FL05095", "FL050DB", "FL050DL",
             "FL050GM", "FL050HP", "FL050MP", "FL05100", "FL05101", "FL05102",
             "FL05103", "FL05104", "FL05105", "FL05106", "FL05140", "FL05190",
             "FL051DB", "FL051DL", "FL051GM", "FL051HP", "FL051MP", "FL05200",
             "FL05201", "FL05202", "FL05203", "FL05204", "FL05205", "FL05206",
             "FL05207", "FL05208", "FL05209", "FL0520S", "FL05210", "FL05211",
             "FL05212", "FL05213", "FL05214", "FL05215", "FL05216", "FL05217",
             "FL05218", "FL05219", "FL05220", "FL05221", "FL05225", "FL05226",
             "FL05227", "FL05228", "FL05229", "FL05316", "FL05240", "FL05250",
             "FL05290", "FL05299", "FL052DB", "FL052DL", "FL052GM", "FL052HP",
             "FL052MP", "FL05300", "FL05301", "FL05302", "FL05303", "FL05304",
             "FL05305", "FL05307", "FL05308", "FL05309", "FL05310", "FL05311",
             "FL05312", "FL05313", "FL05314", "FL05315", "FL05317", "FL05318",
             "FL05340", "FL05350", "FL05390", "FL053DB", "FL053DL", "FL053GM",
             "FL053HP", "FL053MP", "FL05400", "FL05401", "FL05402", "FL05403",
             "FL05404", "FL05405", "FL05440", "FL05490", "FL054DB", "FL054DL",
             "FL054GM", "FL054HP", "FL054MP", "FL05500", "FL05501", "FL05502",
             "FL05503", "FL05504", "FL05505", "FL05507", "FL05540", "FL05590",
             "FL055DB", "FL055DL", "FL055GM", "FL055HP", "FL055MP", "FL05600",
             "FL05601", "FL05602", "FL05640", "FL05650", "FL05690", "FL056DB",
             "FL056DL", "FL056GM", "FL056HP", "FL056MP", "FL05700", "FL05701",
             "FL05702", "FL05703", "FL05740", "FL05790", "FL057DB", "FL057DL",
             "FL057GM", "FL057HP", "FL057MP", "FL05800", "FL05801", "FL05802",
             "FL05803", "FL05804", "FL05806", "FL05807", "FL05840", "FL05850",
             "FL05890", "FL058DB", "FL058DL", "FL058GM", "FL058HP", "FL058MP",
             "FL05900", "FL05901", "FL05902", "FL05903", "FL05904", "FL05905",
             "FL05906", "FL05907", "FL05940", "FL05990", "FL059DB", "FL059DL",
             "FL059GM", "FL059HP", "FL059MP", "FL06000", "FL06001", "FL06002",
             "FL06003", "FL06004", "FL06005", "FL06040", "FL06090", "FL060DB",
             "FL060DL", "FL060GM", "FL060HP", "FL060MP", "FL06100", "FL06101",
             "FL06102", "FL06103", "FL06140", "FL06150", "FL06190", "FL061DB",
             "FL061DL", "FL061GM", "FL061HP", "FL061MP", "FL06200", "FL06201",
             "FL06240", "FL06290", "FL062DB", "FL062DL", "FL062GM", "FL062HP",
             "FL062MP", "FL06300", "FL06340", "FL06390", "FL063DB", "FL063DL",
             "FL063GM", "FL063HP", "FL06400", "FL06401", "FL06402", "FL06403",
             "FL06404", "FL06405", "FL06406", "FL06407", "FL06408", "FL06409",
             "FL06410", "FL06411", "FL06412", "FL06413", "FL06414", "FL06415",
             "FL06416", "FL06417", "FL06440", "FL06450", "FL06490", "FL06491",
             "FL064DB", "FL064DL", "FL064GM", "FL064HP", "FL064MP", "FL06500",
             "FL06502", "FL06540", "FL06590", "FL065DB", "FL065DL", "FL065GM",
             "FL065HP", "FL065MP", "FL06600", "FL06601", "FL06602", "FL06640",
             "FL06690", "FL066DB", "FL066DL", "FL066GM", "FL066HP", "FL066MP",
             "FL06700", "FL06701", "FL06702", "FL06740", "FL06790", "FL067DB",
             "FL067DL", "FL067GM", "FL067HP", "FL067MP", "FLFHP00")


ham(source = source_keys, choice = choice_keys,
    key = id_keys, n = 7, dedupe = TRUE)

